#!/bin/bash
# Docker hub does a recursive clone, then checks the branch out,
# so when a PR adds a submodule (or updates it), it fails.

# Push in case we have new commits or tags
git push origin --tags $SOURCE_BRANCH