#!/bin/bash
# Docker hub does a recursive clone, then checks the branch out,
# so when a PR adds a submodule (or updates it), it fails.

# Auto version incrementing only for Master branch and exlucde commits with msg = [Release] New version $version
echo COMMIT_MSG
echo $COMMIT_MSG

if [[ SOURCE_BRANCH -eq 'master' && $(expr match "$COMMIT_MSG" '\[Release\] Version [\d.]*') > 0 ]]; then
    git push origin --tags master
fi

if [[ SOURCE_BRANCH -eq 'master' && $(expr match "$COMMIT_MSG" '\[Release\] Version [\d.]*') == 0 ]]; then
    git push origin --tags master
fi